### ISSUE TITLE
Loading a mod page when not logged in takes 2-3 seconds

### ISSUE THREAD

**Issue by troy-f** [XivRepo/XivRepo-ApiServer-legacy#13]
**Describe the bug**
Loading a mod page when not logged in takes 2-3 seconds

**To Reproduce**
browse to https://dev.xivrepo.com/mod/test123 in a fresh session.

**Expected behavior**
Loading in like 50-100ms max.

**Comment by troy-f** [comment]
This is the api call that is taking multiple seconds

`https://dev.xivrepo.com/api/v1/mod/nlTNiA5T/version`

**Comment by XNBlank** [comment]
This happens when logged in as well.

**Comment by XNBlank** [comment]
It is no longer slow. 🎉 https://github.com/XivRepo/XivRepo-ApiServer/commit/4d61270c4d75770d8fb94142236f99585726c2e5
