### ISSUE TITLE
Support External Mod Hosting

### ISSUE THREAD

**Issue by AncientAzem** [XivRepo/XivRepo-ApiServer-legacy#18]
Users should be able to host their mod on the repo or externally. See below for information on how this was implemented on the frontend: 

```js
// The follow fields have been added on the version object
{
  hosting_location: String  //can either be `hosted` or `external`
  external_url: String //will only exist on external versions and is a link to the external hosting location
}
```
For more details see https://github.com/XivRepo/XivRepo-Frontend/issues/43

**Comment by XNBlank** [comment]
Added in this commit 
https://github.com/XivRepo/XivRepo-ApiServer/commit/cb4fe38fa778c61b538560721ccc0d34da4b8bbc
